import React,{useState} from 'react';
import {ArrowLeft,ArrowRight,CheckCircle2,AlertTriangle,Terminal,RotateCcw} from 'lucide-react';
export default function ChallengeLab({lab,onBack,onFinish,completed}){
 const [idx,setIdx]=useState(0),[choice,setChoice]=useState(null),[checked,setChecked]=useState(false),[showEvidence,setShowEvidence]=useState(false),[finished,setFinished]=useState(false);
 const current=lab.steps[idx];
 function advance(){if(idx+1===lab.steps.length){setFinished(true);onFinish(lab.id)}else{setIdx(i=>i+1);setChoice(null);setChecked(false)}}
 function restart(){setIdx(0);setChoice(null);setChecked(false);setShowEvidence(false);setFinished(false)}
 return <div className="challenge-detail"><button className="text-button" onClick={onBack}><ArrowLeft size={16}/> All labs</button><div className="deep-banner"><span className="eyebrow">{lab.kind==='design'?'REQUIREMENTS → SERVICES':'TROUBLESHOOTING'} · {lab.level.toUpperCase()}</span><h2>{lab.title}</h2><p>{lab.summary}</p><span className="study-label">{lab.domain}</span></div>
 <div className="lab-layout"><div><section className="reading-section"><h3>Customer context</h3><p>{lab.symptom}</p><p className="muted"><strong>Architecture:</strong> {lab.architecture}</p></section><section className="reading-section"><div className="section-head"><h3>Investigation evidence</h3><button className="btn secondary" onClick={()=>setShowEvidence(x=>!x)}>{showEvidence?'Hide evidence':'Inspect evidence'}</button></div>{showEvidence?<div className="evidence-stack">{lab.evidence.map(e=><div className="evidence" key={e.label}><strong>{e.label}</strong><p>{e.value}</p></div>)}</div>:<p className="muted">Reveal the logs and environment clues, then choose a diagnostic action.</p>}</section>
 {!finished?<section className="reading-section"><div className="section-head"><h3>Decision {idx+1} of {lab.steps.length}</h3><span className="muted tiny">{Math.round((idx)/lab.steps.length*100)}% complete</span></div><div className="progress-track"><div style={{width:(idx/lab.steps.length*100)+'%'}}/></div><p><strong>{current.q}</strong></p><div className="options">{current.o.map((o,i)=><button key={i} disabled={checked} onClick={()=>setChoice(i)} className={'option '+(choice===i?'selected ':'')+(checked&&i===current.a?'right ':checked&&choice===i?'wrong ':'')}><span className="option-letter">{String.fromCharCode(65+i)}</span>{o}</button>)}</div>{checked&&<div className={'answer-note '+(choice===current.a?'success':'failure')}><strong>{choice===current.a?'Correct reasoning':'Revisit the evidence'}</strong><p>{current.why}</p></div>}<div className="quiz-footer">{!checked?<button className="btn primary" disabled={choice===null} onClick={()=>setChecked(true)}>Check decision</button>:<button className="btn primary" onClick={advance}>{idx+1===lab.steps.length?'Finish investigation':'Next decision'} <ArrowRight size={16}/></button>}</div></section>:<section className="reading-section recall"><h3><CheckCircle2 size={20}/> Investigation complete</h3><p><strong>Customer-ready explanation:</strong> {lab.customer}</p><p><strong>Verification:</strong> Confirm the observed symptom is resolved and document evidence.</p><p><strong>Cleanup:</strong> {lab.cleanup}</p><button className="btn secondary" onClick={restart}><RotateCcw size={16}/> Repeat lab</button> {completed&&<span className="muted tiny">Saved to local progress</span>}</section>}</div>
 <aside className="lab-sidebar"><div className="sticky-note"><h3><Terminal size={18}/> Console / CLI companion</h3><pre className="code-area"><code>{lab.cli}</code></pre><p className="muted tiny">Simulation first. These commands are examples to run only in a project you control.</p><hr/><p><AlertTriangle size={16}/> <strong>Safety</strong></p><p className="muted tiny">Resource creation, networking, and databases can incur charges. {lab.cleanup}</p></div></aside></div></div>
}
