import React,{useState} from 'react';
import {ArrowLeft,CheckCircle2,BookOpen,Network,Terminal,ShieldAlert,Lightbulb,ClipboardCheck} from 'lucide-react';
import {deepLessons} from '../data/deepLessons.js';
export default function DeepLesson({lesson,index,onBack,onComplete,completed}){
 const detail=deepLessons[index]; const [choice,setChoice]=useState(null);const [checked,setChecked]=useState(false);
 if(!detail)return null;
 const sections=[{icon:Lightbulb,title:'1 · Why this exists',body:detail.why},{icon:Network,title:'2 · Mental model',body:detail.mental},{icon:BookOpen,title:'4 · Real-world customer scenario',body:detail.scenario},{icon:Lightbulb,title:'5 · Connect to your experience',body:detail.compare},{icon:ShieldAlert,title:'8 · Exam decision rules',body:detail.exam}];
 return <div className="deep-detail"><button className="text-button" onClick={onBack}><ArrowLeft size={16}/> Back to learning paths</button><div className="deep-banner"><span className="eyebrow">PRIMARY STUDY GUIDE · LESSON {index+1}</span><h2>{lesson.t}</h2><p>{lesson.summary}</p><span className="study-label">Learn → Understand → Troubleshoot → Recall</span></div>
 <div className="reading-layout"><article className="reading-main">
 {sections.slice(0,2).map(({icon:Icon,title,body})=><section className="reading-section" key={title}><h3><Icon size={19}/>{title}</h3><p>{body}</p></section>)}
 <section className="reading-section"><h3><Network size={19}/> 3 · How it works, step by step</h3><ol className="explain-steps">{detail.how.map((x,i)=><li key={i}>{x}</li>)}</ol></section>
 {sections.slice(2,4).map(({icon:Icon,title,body})=><section className="reading-section" key={title}><h3><Icon size={19}/>{title}</h3><p>{body}</p></section>)}
 <section className="reading-section"><h3><ShieldAlert size={19}/> 6 · Troubleshooting playbook</h3><ul className="trouble-list">{detail.troubleshoot.map((x,i)=><li key={i}>{x}</li>)}</ul></section>
 <section className="reading-section"><h3><Terminal size={19}/> 7 · Safe CLI investigation</h3><p className="muted tiny">Read-only inspection commands unless noted. Replace placeholders with your project and resource names.</p><pre className="code-area"><code>{detail.command}</code></pre><p className="muted tiny">Use the Google Cloud Console to locate the same resource before running commands. Avoid changing production resources while studying.</p></section>
 {sections.slice(4).map(({icon:Icon,title,body})=><section className="reading-section" key={title}><h3><Icon size={19}/>{title}</h3><p>{body}</p></section>)}
 <section className="reading-section recall"><h3><ClipboardCheck size={19}/> 9 · Check your understanding</h3><p><strong>{detail.check.q}</strong></p><div className="options">{detail.check.o.map((x,i)=><button className={'option '+(choice===i?'selected ':'')+(checked&&i===detail.check.a?'right ':checked&&choice===i?'wrong ':'')} onClick={()=>{if(!checked)setChoice(i)}} key={i}><span className="option-letter">{String.fromCharCode(65+i)}</span>{x}</button>)}</div>{checked&&<div className="answer-note"><strong>{choice===detail.check.a?'Correct':'Review this concept'}</strong><p>{detail.check.why}</p></div>}<div className="quiz-footer"><button className="btn secondary" onClick={()=>{setChoice(null);setChecked(false)}}>Try again</button><button className="btn primary" disabled={choice===null||checked} onClick={()=>setChecked(true)}>Check answer</button></div></section>
 <button className="btn primary" onClick={onComplete}><CheckCircle2 size={17}/>{completed?'Completed ✓':'Mark lesson complete'}</button>
 </article><aside className="reading-aside"><div className="sticky-note"><strong>Study this in three passes</strong><p>1. Read the explanation.</p><p>2. Follow the troubleshooting logic.</p><p>3. Close the notes and explain the service out loud.</p><hr/><strong>Core terms</strong><ul>{lesson.terms.map(x=><li key={x}>{x}</li>)}</ul><p className="muted tiny">This is a study explanation, not a claim that these are official exam questions.</p></div></aside></div></div>
}
