import React,{useEffect,useMemo,useState} from 'react';
import {LayoutDashboard,BookOpen,ClipboardList,BarChart3,Terminal,RotateCcw,ArrowRight,CheckCircle2,Menu,X,Search,ChevronRight,ShieldCheck} from 'lucide-react';
import study from './data/study.json';
import DeepLesson from './components/DeepLesson.jsx';
import ChallengeLab from './components/ChallengeLab.jsx';
import CliTrainer from './components/CliTrainer.jsx';
import {challenges} from './data/challenges.js';
import {loadProgress,persistProgress} from './lib/storage.js';
const {lessons,questions,domains}=study;
const plan=[
 ['Day 1','Setup and IAM','Projects, hierarchy, billing, permissions'],
 ['Day 2','Compute and data','Compute Engine, Cloud Run, databases'],
 ['Day 3','Networking','VPC, subnets, firewalls, VPN, load balancing'],
 ['Day 4','Deployment','gcloud, Artifact Registry, GKE, Terraform'],
 ['Day 5','Operations','Logging, monitoring, backups, recovery'],
 ['Day 6','Security and review','Service accounts, least privilege, weak topics'],
 ['Day 7','Exam rehearsal','Timed practice and final review']
];
const menu=[['dashboard','Dashboard',LayoutDashboard],['lessons','Learn',BookOpen],['practice','Practice',ClipboardList],['labs','Troubleshooting & Design',Terminal],['cli','CLI Trainer',Terminal],['analytics','Progress',BarChart3]];
function Logo(){return <span className="brand-logo"><span className="g-blue">G</span><span className="g-red">o</span><span className="g-yellow">o</span><span className="g-blue">g</span><span className="g-green">l</span><span className="g-red">e</span><span className="brand-cloud"> Cloud</span><span className="brand-rule"/> ACE Study Lab</span>}
function Panel({children,className=''}){return <section className={'panel '+className}>{children}</section>}
function Tag({children,color='blue'}){return <span className={'tag tag-'+color}>{children}</span>}
export default function App(){
 const [page,setPage]=useState('dashboard');const [progress,setProgress]=useState(loadProgress);
 const [openMenu,setOpenMenu]=useState(false);const [selectedLesson,setSelectedLesson]=useState(null);
 const [domainFilter,setDomainFilter]=useState('all'); const [search,setSearch]=useState('');
 const [labId,setLabId]=useState(null);const [labKind,setLabKind]=useState('all');
 const [mode,setMode]=useState('all'); const [quiz,setQuiz]=useState(null); const [answer,setAnswer]=useState(null); const [reveal,setReveal]=useState(false);
 useEffect(()=>persistProgress(progress),[progress]);
 const attempts=progress.attempts||{};
 const attempted=Object.keys(attempts).length;
 const correct=Object.values(attempts).filter(a=>a.correct).length;
 const accuracy=attempted?Math.round(correct/attempted*100):0;
 const filteredLessons=lessons.map((l,id)=>({...l,id})).filter(l=>(domainFilter==='all'||String(l.d)===domainFilter)&&(`${l.t} ${l.summary}`.toLowerCase().includes(search.toLowerCase())));
 const pool=useMemo(()=>questions.map((q,id)=>({...q,id})).filter(q=>domainFilter==='all'||String(q.d)===domainFilter).filter(q=> mode!=='missed'||attempts[q.id]?.correct===false).filter(q=>mode!=='unseen'||!attempts[q.id]),[domainFilter,mode,progress]);
 function record(correctNow,q){setProgress(s=>({...s,attempts:{...s.attempts,[q.id]:{correct:correctNow,choice:answer,at:new Date().toISOString()}},history:[...(s.history||[]).slice(-199),{id:q.id,correct:correctNow,at:new Date().toISOString()}]}));}
 function startQuiz(){if(!pool.length)return;setQuiz({ids:pool.map(x=>x.id).sort(()=>Math.random()-.5),idx:0,score:0,finished:false});setAnswer(null);setReveal(false)}
 const current=quiz&&!quiz.finished?questions[quiz.ids[quiz.idx]]:null;
 function checkAnswer(){if(answer===null||!current||reveal)return;const good=answer===current.a;record(good,{id:quiz.ids[quiz.idx]});setQuiz(q=>({...q,score:q.score+(good?1:0)}));setReveal(true)}
 function nextQuestion(){setAnswer(null);setReveal(false);setQuiz(q=>q.idx+1>=q.ids.length?{...q,finished:true}:{...q,idx:q.idx+1});}
 function nav(id){setPage(id);setOpenMenu(false);setDomainFilter('all');setSearch('');setSelectedLesson(null);setQuiz(null);setLabId(null);}
 const day=Math.max(1,Math.min(7,Math.floor(progress.completed.length/2)+1));
 return <><header className="topbar"><div className="topbar-inner"><button className="hamburger" aria-label="Toggle navigation" onClick={()=>setOpenMenu(x=>!x)}>{openMenu?<X size={23}/>:<Menu size={23}/>}</button><Logo/><nav className={'nav '+(openMenu?'nav-open':'')} aria-label="Main navigation">{menu.map(([id,label,Icon])=><button key={id} className={'nav-link '+(page===id?'nav-active':'')} onClick={()=>nav(id)}><Icon size={16}/>{label}</button>)}</nav><span className="top-count">{questions.length} practice questions</span></div></header>
 <main className="container">
 {page==='dashboard'&&<><div className="hero"><div><div className="eyebrow">GOOGLE CLOUD · ASSOCIATE CLOUD ENGINEER</div><h1>Build your cloud knowledge.</h1><p>Full lessons, troubleshooting investigations, architecture choices, and exam practice in one study guide.</p><button className="btn primary" onClick={()=>nav('practice')}>Open practice <ArrowRight size={17}/></button></div><div className="hero-decoration" aria-hidden="true"><span/><span/><span/><span/></div></div>
 <div className="stats"><Panel><div className="stat-title">Lessons completed</div><strong>{progress.completed.length}<span> / {lessons.length}</span></strong><div className="progress-track"><div style={{width:progress.completed.length/lessons.length*100+'%'}}/></div></Panel><Panel><div className="stat-title">Questions attempted</div><strong>{attempted}<span> / {questions.length}</span></strong><div className="progress-track green"><div style={{width:attempted/questions.length*100+'%'}}/></div></Panel><Panel><div className="stat-title">Accuracy</div><strong>{accuracy}%</strong><p className="muted tiny">Based on latest answer per question</p></Panel><Panel><div className="stat-title">Suggested study day</div><strong>{day}<span> / 7</span></strong><p className="muted tiny">A flexible pace, not a deadline</p></Panel></div>
 <div className="two-col"><Panel><div className="section-head"><h2>Your seven-day plan</h2><Tag>Guided</Tag></div><div className="days">{plan.map(([d,t,desc],i)=><div className={'day '+(i+1===day?'day-current':'')} key={d}><span className="day-no">{i+1}</span><div><strong>{t}</strong><small>{desc}</small></div>{i+1===day&&<Tag color="green">Current</Tag>}</div>)}</div></Panel><Panel><div className="section-head"><h2>Study by exam domain</h2></div><p className="muted">Use the domain guide to focus on topics that need work.</p>{domains.map((d,i)=><button className="domain-row" key={d.name} onClick={()=>{nav('lessons');setDomainFilter(String(i))}}><span className={'domain-dot d'+i}/><span>{d.name}</span><span className="muted tiny">{d.weight}</span><ChevronRight size={15}/></button>)}<div className="info-note">Your source transcripts contain older terminology. The active quiz bank is separate from unverified transcripts.</div></Panel></div></>}
 {page==='lessons'&&<><div className="page-head"><span className="eyebrow">LEARNING CENTER</span><h1>Learn the service, not just the definition</h1><p>Full study-guide lessons with mental models, architecture, troubleshooting, exam strategy, and knowledge checks.</p></div><div className="filters"><label className="search"><Search size={18}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search lessons..."/></label><select aria-label="Filter domain" value={domainFilter} onChange={e=>setDomainFilter(e.target.value)}><option value="all">All domains</option>{domains.map((d,i)=><option value={i} key={i}>{d.name}</option>)}</select></div>{selectedLesson!==null?<DeepLesson key={selectedLesson} lesson={lessons[selectedLesson]} index={selectedLesson} onBack={()=>setSelectedLesson(null)} onComplete={()=>setProgress(s=>({...s,completed:[...new Set([...s.completed,selectedLesson])]}))} completed={progress.completed.includes(selectedLesson)}/>:<><div className="hub-intro"><strong>Study workflow:</strong> Read one full lesson, try the CLI inspections, and finish a related scenario lab. Then use practice questions to test recall.</div><div className="lesson-grid">{filteredLessons.map(l=><button className="lesson-card" key={l.id} onClick={()=>setSelectedLesson(l.id)}><div className="card-top"><Tag>{domains[l.d].name}</Tag>{progress.completed.includes(l.id)?<CheckCircle2 size={19} color="#188038"/>:<span className="muted tiny">Full guide</span>}</div><h3>{l.t}</h3><p>{l.summary}</p><span className="card-action">Open full lesson <ArrowRight size={15}/></span></button>)}</div></>}</>}
 {page==='practice'&&<><div className="page-head"><span className="eyebrow">PRACTICE ENGINE</span><h1>Test what you know</h1><p>{questions.length} interactive practice questions with explanations. Source transcripts are reference material, not automatically trusted answer keys.</p></div>{!quiz?<Panel className="quiz-setup"><h2>Configure your practice session</h2><div className="form-grid"><label>Exam domain<select value={domainFilter} onChange={e=>setDomainFilter(e.target.value)}><option value="all">All domains</option>{domains.map((d,i)=><option key={i} value={i}>{d.name}</option>)}</select></label><label>Practice set<select value={mode} onChange={e=>setMode(e.target.value)}><option value="all">All questions</option><option value="unseen">Not answered yet</option><option value="missed">Incorrect answers only</option></select></label></div><p className="muted">{pool.length} matching questions · One question at a time · Immediate explanations</p><button className="btn primary" onClick={startQuiz} disabled={!pool.length}>Start quiz <ArrowRight size={17}/></button>{!pool.length&&<p>No questions match your filters. Choose a different set.</p>}</Panel>:quiz.finished?<Panel className="quiz-setup"><Tag color="green">Session complete</Tag><h2>{quiz.score} correct out of {quiz.ids.length}</h2><p>Review weak subjects under Progress, or try another set.</p><button className="btn primary" onClick={()=>setQuiz(null)}>Choose another quiz</button></Panel>:<Panel className="quiz-panel"><div className="question-header"><Tag>{domains[current.d].name}</Tag><span className="muted">Question {quiz.idx+1} of {quiz.ids.length}</span></div><div className="progress-track"><div style={{width:(quiz.idx+1)/quiz.ids.length*100+'%'}}/></div><h2>{current.q}</h2><div className="options">{current.o.map((opt,i)=><button key={i} disabled={reveal} onClick={()=>setAnswer(i)} className={'option '+(answer===i?'selected ':'')+(reveal&&i===current.a?'right ':reveal&&answer===i&&i!==current.a?'wrong ':'')}><span className="option-letter">{String.fromCharCode(65+i)}</span><span>{opt}</span></button>)}</div>{reveal&&<div className={'answer-note '+(answer===current.a?'success':'failure')}><strong>{answer===current.a?'Correct':'Not quite'}</strong><p>{current.why}</p>{current.source&&<small>Adapted from {current.source}</small>}</div>}<div className="quiz-footer"><button className="btn secondary" onClick={()=>setQuiz(null)}>End session</button>{reveal?<button className="btn primary" onClick={nextQuestion}>{quiz.idx+1===quiz.ids.length?'See results':'Next question'} <ArrowRight size={16}/></button>:<button disabled={answer===null} className="btn primary" onClick={checkAnswer}>Check answer</button>}</div></Panel>}</>}
 {page==='labs'&&<>{labId!==null?<ChallengeLab key={labId} lab={challenges.find(l=>l.id===labId)} onBack={()=>setLabId(null)} completed={(progress.labs||[]).includes(labId)} onFinish={id=>setProgress(s=>({...s,labs:[...new Set([...(s.labs||[]),id])]}))}/>:<><div className="page-head"><span className="eyebrow">HANDS-ON THINKING · TWO TRACKS</span><h1>Troubleshoot and design Google Cloud</h1><p>Inspect realistic evidence, choose investigative steps, and map customer requirements to services.</p></div><div className="hub-intro"><strong>Start here:</strong> Guided labs use one clear failure or requirement. Advanced labs span multiple services. Simulations do not deploy resources or incur charges.</div><div className="track-tabs">{[['all','All labs'],['troubleshoot','Troubleshooting'],['design','Requirements → Services']].map(([id,label])=><button key={id} className={'track-tab '+(labKind===id?'active':'')} onClick={()=>setLabKind(id)}>{label}</button>)}</div><div className="lab-card-grid">{challenges.filter(l=>labKind==='all'||l.kind===labKind).map(l=><button className="lab-card" key={l.id} onClick={()=>setLabId(l.id)}><div className="lab-head-row"><Tag color={l.level==='Advanced'?'yellow':'blue'}>{l.level}</Tag>{(progress.labs||[]).includes(l.id)&&<CheckCircle2 size={18} color="#188038"/>}</div><small className="muted">{l.domain}</small><h3>{l.title}</h3><p>{l.summary}</p><span className="card-action">Start interactive lab <ArrowRight size={16}/></span></button>)}</div></>}</>}
 {page==='cli'&&<CliTrainer progress={progress} onComplete={id=>setProgress(s=>({...s,cli:[...new Set([...(s.cli||[]),id])]}))}/>}
 {page==='analytics'&&<><div className="page-head"><span className="eyebrow">PROGRESS</span><h1>Your learning signals</h1><p>Accuracy is based on your most recent answer for each question, not a prediction of exam success.</p></div><div className="stats"><Panel><div className="stat-title">Attempted</div><strong>{attempted}</strong></Panel><Panel><div className="stat-title">Correct</div><strong>{correct}</strong></Panel><Panel><div className="stat-title">Needs review</div><strong>{attempted-correct}</strong></Panel><Panel><div className="stat-title">Lesson progress</div><strong>{progress.completed.length}/{lessons.length}</strong></Panel></div><Panel><h2>Performance by domain</h2><p className="muted">Interactive labs completed: {(progress.labs||[]).length} / {challenges.length}</p>{domains.map((d,i)=>{const ids=questions.map((q,k)=>q.d===i?k:null).filter(x=>x!==null);const done=ids.filter(id=>attempts[id]);const good=done.filter(id=>attempts[id].correct);return <div className="performance" key={i}><div className="performance-head"><strong>{d.name}</strong><span>{good.length}/{done.length} correct · {ids.length} available</span></div><div className="progress-track"><div style={{width:(done.length?good.length/done.length*100:0)+'%'}}/></div></div>})}<button className="btn secondary" onClick={()=>{nav('practice');setMode('missed')}}>Practice missed questions <RotateCcw size={15}/></button></Panel></>}
 <footer className="footer"><ShieldCheck size={15}/> Independent learning tool, not affiliated with or endorsed by Google Cloud. Progress stays in this browser.</footer></main></>
}
